{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_cal.TestCal object at 0x000001D9C03A8C40>\n\n    def test_1(self):\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_cal.py:23: AssertionError"}, "start": 1648202627402, "stop": 1648202627403, "uuid": "ec0bf670-e402-4d06-8b13-9ae78afe0c59", "historyId": "9dd1ca9652542d91238e027876196029", "testCaseId": "a173c52803664839bf2c0b698f07a00c", "fullName": "test_pytest.test_cal.TestCal#test_1", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "3372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_cal"}]}