{"name": "test_add_error[Ca_add_012]", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'TypeError'>", "trace": "self = <test_cal.TestCal object at 0x0000029E0208B8E0>, numa = '文', numb = 9.3\nresulted = 'TypeError'\n\n    @pytest.mark.parametrize(\"numa,numb,resulted\", get_errvalue(), ids=get_ekeys())\n    def test_add_error(self, numa, numb, resulted):\n        # 定义一个对象calc\n        calc = Calculator()\n        # result 为实际结果\n>       with pytest.raises(eval(resulted)) as e:\nE       Failed: DID NOT RAISE <class 'TypeError'>\n\ntest_cal.py:41: Failed"}, "parameters": [{"name": "numa", "value": "'文'"}, {"name": "numb", "value": "9.3"}, {"name": "resulted", "value": "'TypeError'"}], "start": 1648451806563, "stop": 1648451806563, "uuid": "e6b2cf14-01a0-44e8-97aa-bd253ef73eb2", "historyId": "43ec30340d6cf91fb6059eb332dcac96", "testCaseId": "a3bfe621045782c9ea9a5de99829cd04", "fullName": "test_pytest.test_cal.TestCal#test_add_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('def_fixture')"}, {"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "19376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_cal"}]}