{"name": "test_wait", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <test_wait.TestWait object at 0x00000290CA298EE0>\n\n    def setup(self):\n>       self.driver = webdriver.chrome()\nE       TypeError: 'module' object is not callable\n\ntest_wait.py:9: TypeError"}, "start": 1648632244280, "stop": 1648632244280, "uuid": "6bec5b21-6a3a-4309-bf6d-15e86cc73d76", "historyId": "b95c9ddf75c50bb477c4f705bb976f92", "testCaseId": "ca27799007501894fc9c9d427189d79c", "fullName": "test_pytest.test_wait.TestWait#test_wait", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_wait"}, {"name": "subSuite", "value": "TestWait"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "17184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_wait"}]}